name: Update Server

on:
  push:
    branches:
      - main

jobs:
  update_server:
    name: Update Server
    runs-on:
    - self-hosted
    - linux
    - x64


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run update script on server
        run: |
          cd /var/www/hemophilia-tracker
          git stash
          git pull origin main

      - name: Restart HT service
        run: |
          echo "${{ secrets.PWD }}" | sudo -S systemctl restart uvicorn-hemophilia-tracker.service 

      - name: Purge Cloudflare Cache
        run: |
          curl --request POST \
            --url https://api.cloudflare.com/client/v4/zones/5e1965e9787dc53fc303f38b301eca0d/purge_cache \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Bearer ${{ secrets.CF_PURGE }}' \
            --data '{"purge_everything": true}'

      - name: Purge Cloudflare Cache automate-everything-company
        run: |
          curl --request POST \
            --url https://api.cloudflare.com/client/v4/zones/1331c771b655f71312c23c90f892a80b/purge_cache \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Bearer ${{ secrets.CF_PURGE }}' \
            --data '{"purge_everything": true}'
