name: Manual Trigger Test

on:
  workflow_dispatch:

jobs:
  test_runner:
    name: Test Runner
    runs-on: self-hosted
    steps:
      - name: Check Runner
        run: echo "Self-hosted runner is working!"
